# Argument if TwistStamped is used or Twist
stamped: true

# PID parameters for linear components
# for x and y, it should just be multiplied by 1.0, because of the commanded velocity from the path (feedforward)
Kp_linear_x: 1.0
Ki_linear_x: 0.0
Kd_linear_x: 0.0

Kp_linear_y: 1.0
Ki_linear_y: 0.0
Kd_linear_y: 0.0

# for z, the PID controller should be used
Kp_linear_z: 1.0
Ki_linear_z: 0.0
Kd_linear_z: 0.0


# PID parameters for angular components
Kp_angular_x: 1.0
Ki_angular_x: 0.0
Kd_angular_x: 0.0

Kp_angular_y: 1.0
Ki_angular_y: 0.0
Kd_angular_y: 0.0

Kp_angular_z: 1.0
Ki_angular_z: 0.0
Kd_angular_z: 0.0